# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BUDEJIE' do

  # use_frameworks!

  # Pods for BUDEJIE
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'pop'
  pod 'ZFPlayer'
end
